name: Refresh exact order count

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: refresh-exact-order-count
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      REFRESH_URL: https://im8-order-count.vercel.app/api/exact-order-count?force=1&minStartIntervalMs=300000
    steps:
      - name: Trigger refresh
        run: |
          set -euxo pipefail
          curl -fsS "$REFRESH_URL" || true

